[build]
  command = "npm install --legacy-peer-deps && npm run build"
  publish = "dist"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "20.11.0"
  NPM_VERSION = "10.2.4"
  # These will be set in Netlify's environment variables
  VITE_FIREBASE_API_KEY = ""
  VITE_FIREBASE_AUTH_DOMAIN = ""
  VITE_FIREBASE_PROJECT_ID = ""
  VITE_FIREBASE_STORAGE_BUCKET = ""
  VITE_FIREBASE_MESSAGING_SENDER_ID = ""
  VITE_FIREBASE_APP_ID = ""
  VITE_FIREBASE_MEASUREMENT_ID = ""
  VITE_APP_NAME = "Your App Name"
  VITE_APP_URL = "https://your-app-url.netlify.app"
  VITE_GEMINI_API_KEY = ""
  
  # Disable secrets scanning for build output
  SECRETS_SCAN_ENABLED = "false"
  
  # Build optimizations
  NODE_OPTIONS = "--max-old-space-size=4096"

[context.production.environment]
  NODE_VERSION = "20.11.0"
  NPM_VERSION = "10.2.4"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["firebase-admin"]

[dev]
  command = "npm run dev"
  publish = "dist"
  targetPort = 5173
  
# Ignore files that might contain secrets
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    
# Ignore secrets in these paths
[build.environment]
  SECRETS_SCAN_OMIT_PATHS = "dist/*, node_modules/*"
  SECRETS_SCAN_OMIT_KEYS = "VITE_APP_NAME, VITE_APP_URL"
  port = 5173
  publish = "dist"
  targetPort = 5173
