[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18.0.0"
  NPM_VERSION = "9.0.0"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["firebase-admin"]

[dev]
  command = "npm run dev"
  port = 5173
  publish = "dist"
  targetPort = 5173
