[build]
  command = "npm install --legacy-peer-deps && npm run build"
  publish = "dist"
  functions = "netlify/functions"

[build.environment]
  # Node.js and NPM versions
  NODE_VERSION = "20.11.0"
  NPM_VERSION = "10.2.4"
  
  # Security and secrets scanning
  SECRETS_SCAN_ENABLED = "false"
  SECRETS_SCAN_OMIT_PATHS = "dist/*, node_modules/*"
  SECRETS_SCAN_OMIT_KEYS = "VITE_APP_NAME, VITE_APP_URL"
  
  # Build optimizations
  NODE_OPTIONS = "--max-old-space-size=4096"

[context.production.environment]
  NODE_VERSION = "20.11.0"
  NPM_VERSION = "10.2.4"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["firebase-admin"]

[dev]
  command = "npm run dev"
  publish = "dist"
  targetPort = 5173
  port = 5173
  
# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
